name: abstracta
favicon: null
layout_spectrum: 0.4592944241594523
typography_spectrum: 0.6463560010306537
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8276318043936044
  lightness: 0.307156776310876
  saturation: 0.6761013276409358
  rhythmicContrast: 0.21290126931853592
purpose: []
